language: ruby
rbenv:
- 2.7.2
addons:
  postgresql: 9.6
env:
  secure: q+OsoWCXFKUAUMUWKsp3Uz3huxjSKOTZ83ckurd25WM5XqvFr/FmjUiyyJQlotZeRgdOU88QNl8RkRmf1LLTLhKzIUe+B/LYaW4LFB8SN67L1xqke17IAgz+H4zwGVWxs/KPDAYATv4rnopuSkhjbVgLohHHZF8jR9ZKswEbnh+nURUOx6KsSyUaEoCEFMLQg8kWuvAahapZ5tNQi3vgfDLD1jVo3l+c8UTxL/0s7gT7IyJ3yxEUO2dmg9dqd/mdHnppZYA4X27Iq0Pp7icdrRwOYpi4Y/l7qpZoZv1E4JgVXNoEL6ZOJWIfMKqsy79pWk80uIzPCr8PvfJnIpnSkrzHdO8UBB+9eJrctdiZl/I+Jpv8kK0x0r2++hoViCKOBX+p5lOa5HB01fNoYx7dJRs2Erd2JQ/pYCybcpU6nXBtVez3vC2cT0globmlpCCgsC7Zm9gbBwjVAAcUFOYu6/LBh92TCvqZbyGdNG4itgKAgSNisedAeVtHCy1O4HDB3dod3/8pT+iTeS4ICcyqgMWO1fqZe5Yhx0vp0qinwgxiLfgODaPN63b33ItIF8kpP3468MAkH7pnWQKta7n7sAaUxaCdOJwzgA/w5ZcrsFbEFLufwx+iYQ2i5Ltksfeld7pLxC3ppKEtkITGuG62iVvVyPoNOpXNz4TGNU92p2g=
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec -fd
deploy:
  provider: heroku
  api_key: 
  app: 
  run: rails db:migrate
