language: ruby
rbenv:
- 2.7.2
addons:
  postgresql: 9.6
env:
  global:
    - secure: Xtcm4tjJVDI5QggdN/PUCmmtFaabMsYCtBH7clv1P5Pg8puSc/skYTBaTjmdYz66408vYKZcQJLz7QOp8XCTsqPGemfxz5fjRsl08MZ3W1eS2h0LRB0nkS3nKxgiVZqmjNBZ96ef2VZxpITEFf1460Td38te+smaqzXXg2oFaVZkH6XcVeu+YgvodGSjOKe1Uu4vBcJlvoDiY4wEItx0kxjyxiF8DpVM01pD5UK0EeY7AhE0muMN693SoYe/Vk2i6kYh1UK5HQYA2tq/Wrz4g+WiKLdv/+o1GvFIVT4xtwN624iy1hIcOBWlRKDbXTI4CHShw/mb1lvks20n1a0EBcgsA0FaaoBPmRhpEZ+adua3vckiOYK6WfrtfItz0JVZBH0awLcziV4Z1twyQp63VRpVVbxKth5GMYGM0agfg+PzJz2Y2+WuL70AVBEPDGyJRvtsIhrff8claYEJHSAWUVDXesKeLhRT1HrqI2dOBrVhlosW4oOfqoPIvSBqW1ZGrQivS6sipMsPXBDm8QO4vjF+f3MsvtoBRcHT0TA0F0BUsZASGQh+dwCdN7Q4fEyd3q84D0zvWmmPkW6xqEML8dllL8uPS7XxK5OJ+PLDdZ9AUVK83ExU22C1024Ph7ocsOiWllKdGppiBMLv4VNaqcySwXJD0SPVutCytD3PaaY=
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec -fd
deploy:
  provider: heroku
  api_key:
  app:
  run: rails db:migrate
