language: ruby
rbenv:
- 2.7.2
addons:
  postgresql: 9.6
env:
  secure: q+OsoWCXFKUAUMUWKsp3Uz3huxjSKOTZ83ckurd25WM5XqvFr/FmjUiyyJQlotZeRgdOU88QNl8RkRmf1LLTLhKzIUe+B/LYaW4LFB8SN67L1xqke17IAgz+H4zwGVWxs/KPDAYATv4rnopuSkhjbVgLohHHZF8jR9ZKswEbnh+nURUOx6KsSyUaEoCEFMLQg8kWuvAahapZ5tNQi3vgfDLD1jVo3l+c8UTxL/0s7gT7IyJ3yxEUO2dmg9dqd/mdHnppZYA4X27Iq0Pp7icdrRwOYpi4Y/l7qpZoZv1E4JgVXNoEL6ZOJWIfMKqsy79pWk80uIzPCr8PvfJnIpnSkrzHdO8UBB+9eJrctdiZl/I+Jpv8kK0x0r2++hoViCKOBX+p5lOa5HB01fNoYx7dJRs2Erd2JQ/pYCybcpU6nXBtVez3vC2cT0globmlpCCgsC7Zm9gbBwjVAAcUFOYu6/LBh92TCvqZbyGdNG4itgKAgSNisedAeVtHCy1O4HDB3dod3/8pT+iTeS4ICcyqgMWO1fqZe5Yhx0vp0qinwgxiLfgODaPN63b33ItIF8kpP3468MAkH7pnWQKta7n7sAaUxaCdOJwzgA/w5ZcrsFbEFLufwx+iYQ2i5Ltksfeld7pLxC3ppKEtkITGuG62iVvVyPoNOpXNz4TGNU92p2g=
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec -fd
deploy:
  provider: heroku
  api_key:
    secure: Dmg7C97PfqrMTk7huLG593GZe8tE8kzSdkVia4h0Qa3ysrCZ6vm8ZOWDsJWYQjml0ZnVbFNM+05jG3utd+pS1GHQ72J9lsDTrUwma3pKFYkc2EnUpEjDOpBc+CD1fmphaaQtc7CEKRm+yNh9VePZ7fbz89aYg/lUzJo8dxpsLaWnVgQO94jexbGDLHRQKRK8JwKd3AA1HOPk0iHfq+QNuaC1DSAldg+w9L/cTihrc3ZFDSnWwNTXKRzVk/Eu+ZaRPjuk+hiWva6aZMBShGaEi7e5jdTcOqidqF91xMm5Db7XJ7f8fKV7HAc0NtNEm2aSHBUEyxT8mAi4MI6FL7uLVtWdtObTmdMA2LC6vA3NbWxGsYzhOzXAoIHi4BDtJ1dXJVotaQN5IId1YXr4RnVbqIw14DVoqmMhCVMTrJZxr/Blor8fv0L5eBlzB5Y4X0q37X4UxChRQSKHcM94XwByKfdrJFa91k0J5P0J8dsV4/CRhDlNnBPZ89NxtYo1uLg95LNz4VD63RaCYBjbYrW27GrADzXXF7UyLVyu3PbLrmnEqrvB05mTLOTfsNuKfyjcwt5UlMLKMQhRF9CVZP9T1O4pZoABZGUrsN5MY/gDjgVuWE4mSiNDMlSTFHBosTng1aA1z6pNkdZB/Tfer2UUXNxewQIwRAeiQARIMRsTqcI=
  app: t-d-viewing-party
  on: main
  run: rake db:migrate
